[package]
name = "wol"
version = "0.1.0"
edition = "2021"
license = "WTFPL"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wake-on-lan = "0.2.0"
dns-lookup = "2.0.4"
